### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by sclair85** [sclair85/Sam-s-Project#1]
We're having issues with this one. Could we get feedback? @alexgilmer

**Comment by alexgilmer** [comment]
Mr. @sclair85 this is your feedback: Jabberwocky slims. They do everything.  I happen to be an expert, and I'd love to solve this issue for you!

**Comment by sclair85** [comment]
Thank you @alexgilmer. I'm looking forward to getting to know more about Jabberwocky slims.
